//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_COMMERCE_WEBSITE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecommercewebsiteDatabaseEntities : DbContext
    {
        public ecommercewebsiteDatabaseEntities()
            : base("name=ecommercewebsiteDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductTable> ProductTables { get; set; }
        public virtual DbSet<RequestPurchaseTable> RequestPurchaseTables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
    }
}
