//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_COMMERCE_WEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestPurchaseTable: ProductTable
    {
        public int RequestId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductQty { get; set; }
        public Nullable<decimal> ProductAmt { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<int> TrackingId { get; set; }
        public string DeliveryNote { get; set; }
        public Nullable<int> CartProductQty { get; set; }
    }
}
