//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_COMMERCE_WEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ShippingAddress { get; set; }
        public string CaedDetails { get; set; }
        public string PurchaseHistory { get; set; }
        // this will help transfer product info to login action
        public Nullable<int> ProductId { get; set; }
        public string ConfirmPassword { get; set; }

    }
}
